#ESTE es el entorno deploy para la base de datos en Aiven, es importante no modificarlo a menos que se 
#tenga conocimiento de lo que se esta haciendo, ya que esto puede afectar el funcionamiento de la aplicación.

spring.datasource.url=jdbc:mysql://mysql-ds3-samuegonza737-7ae7.a.aivencloud.com:14181/tienda_PCFORGE

spring.datasource.username=avnadmin

spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Agrega esta línea para solucionar el error de SEQUENCES:
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect